import type { Solution } from "./solutions";

export const mockSolutions: Solution[] = [
  {
    id: "canvas-robotics",
    name: "Canvas Robotics",
    tagline: "Autonomous drywall finishing robots",
    description: "Canvas develops intelligent robots that automate drywall finishing in commercial construction. Their AI-powered systems work alongside human crews to increase productivity while maintaining quality standards. The robots use advanced sensors and machine learning to navigate job sites and perform precise finishing work.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Robotics", "AI", "Productivity"],
    region: ["North America"],
    verticals: ["Commercial", "Hospital", "Datacenter"],
    location: "San Francisco, CA",
    founded: "2017",
    teamSize: "50-100",
    website: "canvas.build",
    features: [
      "Autonomous navigation on active job sites",
      "AI-powered quality control and inspection",
      "Seamless integration with existing workflows",
      "Real-time progress tracking and reporting",
    ],
    useCases: [
      "Commercial office buildings",
      "Multi-family residential projects",
      "Healthcare facilities",
      "Educational institutions",
    ],
    relatedIds: ["dusty-robotics", "spot-ai"],
  },
  {
    id: "dusty-robotics",
    name: "Dusty Robotics",
    tagline: "Robotic layout automation for construction",
    description: "Dusty Robotics creates autonomous robots that print precise layout information directly on job site floors. Their FieldPrinter technology eliminates manual measuring and marking, reducing errors and saving significant time on construction projects. The system integrates with BIM models for accurate, real-time layout.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Robotics", "Layout", "Productivity"],
    region: ["North America", "Europe"],
    verticals: ["Commercial", "Datacenter", "Hospital", "Industrial"],
    location: "Mountain View, CA",
    founded: "2018",
    teamSize: "30-50",
    website: "dustyrobotics.com",
    features: [
      "BIM-to-field layout automation",
      "Millimeter-level precision printing",
      "Multi-trade coordination visualization",
      "Cloud-based project management",
    ],
    useCases: [
      "MEP coordination and layout",
      "Structural layout verification",
      "Interior partition layout",
      "Quality control inspections",
    ],
    relatedIds: ["siteprint", "rugged-robotics", "cyphra"],
  },
  {
    id: "spot-ai",
    name: "SPOT AI",
    tagline: "AI-powered construction site safety and surveillance",
    description: "SPOT AI provides intelligent video surveillance and safety monitoring for construction sites. Their cloud-based platform uses computer vision and AI to detect safety violations, monitor progress, and enhance site security. The system provides real-time alerts and comprehensive analytics to improve safety outcomes.",
    logo: "@assets/generated_images/SPOT_AI_company_logo_b81b7511.png",
    categories: ["Safety", "AI"],
    region: ["North America", "Europe", "Asia Pacific"],
    verticals: ["Commercial", "Industrial", "Infrastructure", "Datacenter"],
    location: "San Francisco, CA",
    founded: "2018",
    teamSize: "100-200",
    website: "spot.ai",
    features: [
      "Real-time safety violation detection",
      "PPE compliance monitoring",
      "Automated incident documentation",
      "Intelligent search across video footage",
    ],
    useCases: [
      "Worker safety compliance monitoring",
      "Site security and theft prevention",
      "Progress documentation and timelapse",
      "Quality assurance inspections",
    ],
    relatedIds: ["cyphra", "canvas-robotics"],
  },
  {
    id: "cyphra",
    name: "Cyphra",
    tagline: "AI-driven construction analytics and insights",
    description: "Cyphra leverages artificial intelligence to transform construction data into actionable insights. Their platform analyzes project information from multiple sources to predict delays, optimize schedules, and improve decision-making. The system helps teams identify risks early and maintain project momentum.",
    logo: "@assets/generated_images/Cyphra_company_logo_1a6281cd.png",
    categories: ["AI", "Productivity", "Scheduling"],
    region: ["North America"],
    verticals: ["Commercial", "Industrial", "Infrastructure"],
    location: "Austin, TX",
    founded: "2019",
    teamSize: "20-30",
    website: "cyphra.ai",
    features: [
      "Predictive project analytics",
      "Automated risk identification",
      "Schedule optimization algorithms",
      "Multi-source data integration",
    ],
    useCases: [
      "Project delay prediction and mitigation",
      "Resource allocation optimization",
      "Budget variance analysis",
      "Subcontractor performance tracking",
    ],
    relatedIds: ["spot-ai", "dusty-robotics"],
  },
  {
    id: "siteprint",
    name: "SitePrint",
    tagline: "Robotic layout printing for construction sites",
    description: "SitePrint delivers robotic layout solutions that automate the transfer of digital plans to physical job sites. Their autonomous robots print layout marks with precision, reducing labor costs and improving accuracy in commercial and industrial construction projects.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Robotics", "Layout", "Productivity"],
    region: ["North America"],
    verticals: ["Commercial", "Industrial", "Datacenter"],
    location: "Denver, CO",
    founded: "2019",
    teamSize: "15-25",
    website: "siteprint.io",
    features: [
      "Automated layout printing from BIM",
      "High-precision robotic navigation",
      "Multi-floor capability",
      "Digital verification and documentation",
    ],
    useCases: [
      "MEP layout for datacenters",
      "Commercial building interior layout",
      "Industrial facility construction",
      "Quality control and verification",
    ],
    relatedIds: ["dusty-robotics", "rugged-robotics"],
  },
  {
    id: "rugged-robotics",
    name: "Rugged Robotics",
    tagline: "Precision layout robots for construction",
    description: "Rugged Robotics provides robotic layout solutions that bring digital designs to life on construction sites. Their autonomous robots work overnight to mark precise layouts, enabling faster construction with fewer errors and rework.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Robotics", "Layout", "Productivity"],
    region: ["North America", "Europe"],
    verticals: ["Commercial", "Hospital", "Datacenter", "Airport"],
    location: "Houston, TX",
    founded: "2018",
    teamSize: "25-35",
    website: "ruggedrobotics.com",
    features: [
      "24/7 autonomous operation",
      "BIM-integrated layout printing",
      "Multi-trade coordination support",
      "Cloud-based progress tracking",
    ],
    useCases: [
      "Airport terminal construction",
      "Hospital and healthcare facilities",
      "Mission-critical datacenter builds",
      "Large-scale commercial projects",
    ],
    relatedIds: ["dusty-robotics", "siteprint"],
  },
  {
    id: "procore",
    name: "Procore",
    tagline: "Construction management platform",
    description: "Procore is a comprehensive construction management software platform that connects teams, data, and workflows across the project lifecycle. Used globally across all construction verticals for project management, quality, and safety.",
    logo: "@assets/generated_images/SPOT_AI_company_logo_b81b7511.png",
    categories: ["Productivity", "Scheduling"],
    region: ["North America", "Europe", "Asia Pacific", "Latin America"],
    verticals: ["Commercial", "Industrial", "Infrastructure", "Residential", "Hospital", "Airport", "Datacenter"],
    location: "Carpinteria, CA",
    founded: "2002",
    teamSize: "1000+",
    website: "procore.com",
    features: [
      "Project management and scheduling",
      "Document management and RFIs",
      "Budget tracking and cost control",
      "Quality and safety management",
    ],
    useCases: [
      "Enterprise construction management",
      "Multi-project portfolio tracking",
      "Subcontractor coordination",
      "Owner and GC collaboration",
    ],
    relatedIds: ["cyphra"],
  },
  {
    id: "buildertrend",
    name: "Buildertrend",
    tagline: "Construction project management software",
    description: "Buildertrend provides cloud-based construction project management software designed for home builders, remodelers, and specialty contractors. The platform streamlines communication, scheduling, and financial management.",
    logo: "@assets/generated_images/Cyphra_company_logo_1a6281cd.png",
    categories: ["Productivity", "Scheduling", "Estimating"],
    region: ["North America"],
    verticals: ["Residential", "Commercial"],
    location: "Omaha, NE",
    founded: "2006",
    teamSize: "500-1000",
    website: "buildertrend.com",
    features: [
      "Customer management and communication",
      "Estimating and bidding tools",
      "Schedule and task management",
      "Financial tracking and invoicing",
    ],
    useCases: [
      "Residential construction management",
      "Remodeling projects",
      "Custom home building",
      "Small commercial projects",
    ],
    relatedIds: ["procore"],
  },
  {
    id: "plangrid",
    name: "PlanGrid",
    tagline: "Construction productivity software",
    description: "PlanGrid (now part of Autodesk Construction Cloud) is a construction productivity software that provides digital blueprints, punch lists, and field collaboration tools. Widely used across commercial and infrastructure projects.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Productivity"],
    region: ["North America", "Europe", "Asia Pacific"],
    verticals: ["Commercial", "Infrastructure", "Industrial", "Datacenter"],
    location: "San Francisco, CA",
    founded: "2011",
    teamSize: "200-500",
    website: "plangrid.com",
    features: [
      "Digital blueprint management",
      "Real-time collaboration",
      "Punch list and issue tracking",
      "As-built documentation",
    ],
    useCases: [
      "Field coordination and communication",
      "Quality control inspections",
      "Datacenter construction documentation",
      "Infrastructure project management",
    ],
    relatedIds: ["procore"],
  },
  {
    id: "esticom",
    name: "Esticom",
    tagline: "Cloud-based construction estimating",
    description: "Esticom provides cloud-based takeoff and estimating software designed for electrical, mechanical, and general contractors. The platform streamlines the estimating process with digital plan management and automated calculations.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Estimating", "Productivity"],
    region: ["North America"],
    verticals: ["Commercial", "Industrial", "Datacenter"],
    location: "San Diego, CA",
    founded: "2013",
    teamSize: "20-50",
    website: "esticom.com",
    features: [
      "Digital takeoff and measurement",
      "Electrical and MEP estimating",
      "Cloud-based collaboration",
      "Integration with accounting systems",
    ],
    useCases: [
      "Electrical contractor estimating",
      "MEP bid preparation",
      "Datacenter systems estimation",
      "Commercial project takeoffs",
    ],
    relatedIds: ["procore"],
  },
];
