import type { Solution } from "./solutions";

export interface Project {
  id: string;
  name: string;
  code: string;
  vertical: string;
  location: string;
  value: string;
  status: "Planning" | "In Progress" | "Completed";
  solutionIds: string[];
  description: string;
}

export const mockProjects: Project[] = [
  {
    id: "dc-alpha-2024",
    name: "Alpha Datacenter Expansion",
    code: "DC-ALPHA-2024",
    vertical: "Datacenter",
    location: "Ashburn, VA",
    value: "$125M",
    status: "In Progress",
    solutionIds: ["dusty-robotics", "siteprint", "esticom", "procore", "spot-ai"],
    description: "150,000 sq ft datacenter expansion with advanced MEP systems and redundant power infrastructure"
  },
  {
    id: "hosp-mercy-wing",
    name: "Mercy Hospital New Wing",
    code: "HOSP-MERCY-2024",
    vertical: "Hospital",
    location: "Boston, MA",
    value: "$85M",
    status: "In Progress",
    solutionIds: ["canvas-robotics", "dusty-robotics", "procore", "buildertrend", "plangrid"],
    description: "State-of-the-art 5-story hospital wing with 120 patient rooms and specialized surgical facilities"
  },
  {
    id: "airport-term-b",
    name: "International Airport Terminal B Renovation",
    code: "APT-INTL-TB",
    vertical: "Airport",
    location: "Denver, CO",
    value: "$220M",
    status: "Planning",
    solutionIds: ["dusty-robotics", "spot-ai", "procore", "esticom"],
    description: "Complete renovation of Terminal B including modernized concourses, retail spaces, and security systems"
  },
  {
    id: "comm-tower-plaza",
    name: "Tower Plaza Office Complex",
    code: "COMM-TP-2024",
    vertical: "Commercial",
    location: "Austin, TX",
    value: "$95M",
    status: "In Progress",
    solutionIds: ["canvas-robotics", "cyphra", "procore", "buildertrend"],
    description: "Mixed-use development with Class A office space, retail, and underground parking"
  },
  {
    id: "dc-phoenix-cloud",
    name: "Phoenix Cloud Datacenter",
    code: "DC-PHX-C01",
    vertical: "Datacenter",
    location: "Phoenix, AZ",
    value: "$180M",
    status: "In Progress",
    solutionIds: ["rugged-robotics", "siteprint", "spot-ai", "esticom", "procore"],
    description: "Hyperscale datacenter facility with 250,000 sq ft of raised floor space and liquid cooling systems"
  },
  {
    id: "ind-mfg-plant",
    name: "Advanced Manufacturing Facility",
    code: "IND-MFG-01",
    vertical: "Industrial",
    location: "Detroit, MI",
    value: "$150M",
    status: "Planning",
    solutionIds: ["dusty-robotics", "spot-ai", "procore"],
    description: "350,000 sq ft manufacturing facility with automated assembly lines and clean room spaces"
  }
];

export const mockSolutions: Solution[] = [
  {
    id: "canvas-robotics",
    name: "Canvas Robotics",
    tagline: "Autonomous drywall finishing robots",
    description: "Canvas develops intelligent robots that automate drywall finishing in commercial construction. Their AI-powered systems work alongside human crews to increase productivity while maintaining quality standards. The robots use advanced sensors and machine learning to navigate job sites and perform precise finishing work.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Robotics", "AI", "Productivity"],
    region: ["North America"],
    verticals: ["Commercial", "Hospital", "Datacenter"],
    location: "San Francisco, CA",
    founded: "2017",
    teamSize: "50-100",
    website: "canvas.build",
    features: [
      "Autonomous navigation on active job sites",
      "AI-powered quality control and inspection",
      "Seamless integration with existing workflows",
      "Real-time progress tracking and reporting",
    ],
    useCases: [
      "Commercial office buildings",
      "Multi-family residential projects",
      "Healthcare facilities",
      "Educational institutions",
    ],
    relatedIds: ["dusty-robotics", "spot-ai"],
    primaryDivision: "09",
    baseScore: 95,
    averageCost: "$$$",
    rating: 4.8,
    projectsUsed: 156,
    contactName: "Sales Team",
    contactEmail: "hello@canvas.build",
    contactPhone: "(415) 555-0123",
    media: {
      images: [
        { url: "https://images.unsplash.com/photo-1581094794329-c8112d108627?w=800", caption: "Canvas robot performing automated drywall finishing" },
        { url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800", caption: "Robot working alongside construction crew" },
        { url: "https://images.unsplash.com/photo-1590393769985-53c3538f2866?w=800", caption: "Finished commercial office interior" },
      ],
      videos: [
        { youtubeId: "FxQTY-W6GIo", title: "Canvas Robot in Action", description: "See how our autonomous robot transforms drywall finishing on commercial projects" },
        { youtubeId: "2kpe0KLg7w8", title: "Customer Success Story", description: "Major contractor shares their experience using Canvas robots" },
      ],
      caseStudies: [
        {
          title: "San Francisco Office Tower",
          description: "Canvas robots completed drywall finishing 40% faster than traditional methods on this 20-story commercial project.",
          projectType: "Commercial Office",
          results: "40% time savings, 25% cost reduction, zero defects",
        },
        {
          title: "Healthcare Facility Expansion",
          description: "Delivered consistent, high-quality finishing across 200,000 sq ft of hospital space during occupied renovation.",
          projectType: "Healthcare",
          results: "Maintained schedule, improved quality scores, minimal disruption",
        },
      ],
    },
  },
  {
    id: "dusty-robotics",
    name: "Dusty Robotics",
    tagline: "Robotic layout automation for construction",
    description: "Dusty Robotics creates autonomous robots that print precise layout information directly on job site floors. Their FieldPrinter technology eliminates manual measuring and marking, reducing errors and saving significant time on construction projects. The system integrates with BIM models for accurate, real-time layout.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Robotics", "Layout", "Productivity"],
    region: ["North America", "Europe"],
    verticals: ["Commercial", "Datacenter", "Hospital", "Industrial"],
    location: "Mountain View, CA",
    founded: "2018",
    teamSize: "30-50",
    website: "dustyrobotics.com",
    features: [
      "BIM-to-field layout automation",
      "Millimeter-level precision printing",
      "Multi-trade coordination visualization",
      "Cloud-based project management",
    ],
    useCases: [
      "MEP coordination and layout",
      "Structural layout verification",
      "Interior partition layout",
      "Quality control inspections",
    ],
    relatedIds: ["siteprint", "rugged-robotics", "cyphra"],
    primaryDivision: "01",
    secondaryDivisions: ["22", "23", "26"],
    baseScore: 98,
    averageCost: "$$$$",
    rating: 4.9,
    projectsUsed: 284,
    contactName: "Enterprise Sales",
    contactEmail: "sales@dustyrobotics.com",
    contactPhone: "(650) 555-0142",
    media: {
      images: [
        { url: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?w=800", caption: "Dusty FieldPrinter robot on datacenter project" },
        { url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800", caption: "Precision MEP layout markings on concrete floor" },
        { url: "https://images.unsplash.com/photo-1613545325268-9265e242f1e5?w=800", caption: "BIM model coordination view" },
      ],
      videos: [
        { youtubeId: "u7qRD6AWFVY", title: "FieldPrinter Technology Overview", description: "How Dusty's robotic layout system transforms construction accuracy" },
        { youtubeId: "wLP_Po0htkE", title: "Datacenter Case Study", description: "See how Dusty helped complete a major datacenter ahead of schedule" },
      ],
      caseStudies: [
        {
          title: "Hyperscale Datacenter Layout",
          description: "Dusty robots laid out 500,000+ MEP points with millimeter precision across 250,000 sq ft, eliminating costly rework.",
          projectType: "Datacenter",
          results: "95% reduction in layout time, zero layout-related RFIs, 3 weeks ahead of schedule",
        },
        {
          title: "Hospital MEP Coordination",
          description: "Complex MEP systems coordinated and laid out across 8 floors of critical healthcare infrastructure.",
          projectType: "Healthcare",
          results: "100% first-time quality, saved 6 weeks, improved trade coordination",
        },
      ],
    },
  },
  {
    id: "spot-ai",
    name: "SPOT AI",
    tagline: "AI-powered construction site safety and surveillance",
    description: "SPOT AI provides intelligent video surveillance and safety monitoring for construction sites. Their cloud-based platform uses computer vision and AI to detect safety violations, monitor progress, and enhance site security. The system provides real-time alerts and comprehensive analytics to improve safety outcomes.",
    logo: "@assets/generated_images/SPOT_AI_company_logo_b81b7511.png",
    categories: ["Safety", "AI"],
    region: ["North America", "Europe", "Asia Pacific"],
    verticals: ["Commercial", "Industrial", "Infrastructure", "Datacenter"],
    location: "San Francisco, CA",
    founded: "2018",
    teamSize: "100-200",
    website: "spot.ai",
    features: [
      "Real-time safety violation detection",
      "PPE compliance monitoring",
      "Automated incident documentation",
      "Intelligent search across video footage",
    ],
    media: {
      images: [
        { url: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=800", caption: "AI-powered camera monitoring construction site" },
        { url: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800", caption: "Real-time safety dashboard interface" },
        { url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800", caption: "Workers with proper PPE on monitored site" },
      ],
      videos: [
        { youtubeId: "Hw8FaK6IoHs", title: "SPOT AI Platform Demo", description: "Complete walkthrough of the AI-powered safety monitoring platform" },
        { youtubeId: "j7DKWT1Kmq8", title: "Safety Success Story", description: "How one contractor reduced incidents by 60% with SPOT AI" },
      ],
      caseStudies: [
        {
          title: "Major Infrastructure Project Safety",
          description: "Deployed across 15 active zones on a $500M infrastructure project, SPOT AI detected and prevented numerous safety incidents.",
          projectType: "Infrastructure",
          results: "60% reduction in safety incidents, 100% PPE compliance, saved 2 lives",
        },
        {
          title: "Industrial Facility Construction",
          description: "Monitored high-risk activities including elevated work and heavy equipment operations across 50-acre industrial site.",
          projectType: "Industrial Manufacturing",
          results: "Zero lost-time accidents, improved safety culture, real-time incident response",
        },
      ],
    },
    useCases: [
      "Worker safety compliance monitoring",
      "Site security and theft prevention",
      "Progress documentation and timelapse",
      "Quality assurance inspections",
    ],
    relatedIds: ["cyphra", "canvas-robotics"],
    primaryDivision: "28",
    secondaryDivisions: ["01"],
    baseScore: 92,
    averageCost: "$$$",
    rating: 4.7,
    projectsUsed: 312,
    contactName: "Business Development",
    contactEmail: "contact@spot.ai",
    contactPhone: "(415) 555-0198",
  },
  {
    id: "cyphra",
    name: "Cyphra",
    tagline: "AI-driven construction analytics and insights",
    description: "Cyphra leverages artificial intelligence to transform construction data into actionable insights. Their platform analyzes project information from multiple sources to predict delays, optimize schedules, and improve decision-making. The system helps teams identify risks early and maintain project momentum.",
    logo: "@assets/generated_images/Cyphra_company_logo_1a6281cd.png",
    categories: ["AI", "Productivity", "Scheduling"],
    region: ["North America"],
    verticals: ["Commercial", "Industrial", "Infrastructure"],
    location: "Austin, TX",
    founded: "2019",
    teamSize: "20-30",
    website: "cyphra.ai",
    features: [
      "Predictive project analytics",
      "Automated risk identification",
      "Schedule optimization algorithms",
      "Multi-source data integration",
    ],
    useCases: [
      "Project delay prediction and mitigation",
      "Resource allocation optimization",
      "Budget variance analysis",
      "Subcontractor performance tracking",
    ],
    relatedIds: ["spot-ai", "dusty-robotics"],
    primaryDivision: "01",
    baseScore: 85,
    averageCost: "$$",
    rating: 4.5,
    projectsUsed: 127,
    contactName: "Solutions Team",
    contactEmail: "info@cyphra.ai",
    contactPhone: "(512) 555-0176",
  },
  {
    id: "siteprint",
    name: "SitePrint",
    tagline: "Robotic layout printing for construction sites",
    description: "SitePrint delivers robotic layout solutions that automate the transfer of digital plans to physical job sites. Their autonomous robots print layout marks with precision, reducing labor costs and improving accuracy in commercial and industrial construction projects.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Robotics", "Layout", "Productivity"],
    region: ["North America"],
    verticals: ["Commercial", "Industrial", "Datacenter"],
    location: "Denver, CO",
    founded: "2019",
    teamSize: "15-25",
    website: "siteprint.io",
    features: [
      "Automated layout printing from BIM",
      "High-precision robotic navigation",
      "Multi-floor capability",
      "Digital verification and documentation",
    ],
    useCases: [
      "MEP layout for datacenters",
      "Commercial building interior layout",
      "Industrial facility construction",
      "Quality control and verification",
    ],
    relatedIds: ["dusty-robotics", "rugged-robotics"],
    primaryDivision: "01",
    secondaryDivisions: ["22", "23", "26"],
    baseScore: 88,
    averageCost: "$$$",
    rating: 4.6,
    projectsUsed: 98,
    contactName: "Customer Success",
    contactEmail: "team@siteprint.io",
    contactPhone: "(720) 555-0154",
  },
  {
    id: "rugged-robotics",
    name: "Rugged Robotics",
    tagline: "Precision layout robots for construction",
    description: "Rugged Robotics provides robotic layout solutions that bring digital designs to life on construction sites. Their autonomous robots work overnight to mark precise layouts, enabling faster construction with fewer errors and rework.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Robotics", "Layout", "Productivity"],
    region: ["North America", "Europe"],
    verticals: ["Commercial", "Hospital", "Datacenter", "Airport"],
    location: "Houston, TX",
    founded: "2018",
    teamSize: "25-35",
    website: "ruggedrobotics.com",
    features: [
      "24/7 autonomous operation",
      "BIM-integrated layout printing",
      "Multi-trade coordination support",
      "Cloud-based progress tracking",
    ],
    useCases: [
      "Airport terminal construction",
      "Hospital and healthcare facilities",
      "Mission-critical datacenter builds",
      "Large-scale commercial projects",
    ],
    relatedIds: ["dusty-robotics", "siteprint"],
    primaryDivision: "01",
    secondaryDivisions: ["22", "23", "26"],
    baseScore: 90,
    averageCost: "$$$",
    rating: 4.7,
    projectsUsed: 203,
    contactName: "Partner Relations",
    contactEmail: "partners@ruggedrobotics.com",
    contactPhone: "(713) 555-0189",
  },
  {
    id: "procore",
    name: "Procore",
    tagline: "Construction management platform",
    description: "Procore is a comprehensive construction management software platform that connects teams, data, and workflows across the project lifecycle. Used globally across all construction verticals for project management, quality, and safety.",
    logo: "@assets/generated_images/SPOT_AI_company_logo_b81b7511.png",
    categories: ["Productivity", "Scheduling"],
    region: ["North America", "Europe", "Asia Pacific", "Latin America"],
    verticals: ["Commercial", "Industrial", "Infrastructure", "Residential", "Hospital", "Airport", "Datacenter"],
    location: "Carpinteria, CA",
    founded: "2002",
    teamSize: "1000+",
    website: "procore.com",
    features: [
      "Project management and scheduling",
      "Document management and RFIs",
      "Budget tracking and cost control",
      "Quality and safety management",
    ],
    useCases: [
      "Enterprise construction management",
      "Multi-project portfolio tracking",
      "Subcontractor coordination",
      "Owner and GC collaboration",
    ],
    relatedIds: ["cyphra"],
    primaryDivision: "01",
    baseScore: 100,
    averageCost: "$$$$$",
    rating: 4.9,
    projectsUsed: 1247,
    contactName: "Enterprise Sales",
    contactEmail: "sales@procore.com",
    contactPhone: "(805) 555-0100",
  },
  {
    id: "buildertrend",
    name: "Buildertrend",
    tagline: "Construction project management software",
    description: "Buildertrend provides cloud-based construction project management software designed for home builders, remodelers, and specialty contractors. The platform streamlines communication, scheduling, and financial management.",
    logo: "@assets/generated_images/Cyphra_company_logo_1a6281cd.png",
    categories: ["Productivity", "Scheduling", "Estimating"],
    region: ["North America"],
    verticals: ["Residential", "Commercial"],
    location: "Omaha, NE",
    founded: "2006",
    teamSize: "500-1000",
    website: "buildertrend.com",
    features: [
      "Customer management and communication",
      "Estimating and bidding tools",
      "Schedule and task management",
      "Financial tracking and invoicing",
    ],
    useCases: [
      "Residential construction management",
      "Remodeling projects",
      "Custom home building",
      "Small commercial projects",
    ],
    relatedIds: ["procore"],
    primaryDivision: "01",
    baseScore: 87,
    averageCost: "$$$$",
    rating: 4.6,
    projectsUsed: 892,
    contactName: "Sales Department",
    contactEmail: "sales@buildertrend.com",
    contactPhone: "(402) 555-0167",
  },
  {
    id: "plangrid",
    name: "PlanGrid",
    tagline: "Construction productivity software",
    description: "PlanGrid (now part of Autodesk Construction Cloud) is a construction productivity software that provides digital blueprints, punch lists, and field collaboration tools. Widely used across commercial and infrastructure projects.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Productivity"],
    region: ["North America", "Europe", "Asia Pacific"],
    verticals: ["Commercial", "Infrastructure", "Industrial", "Datacenter"],
    location: "San Francisco, CA",
    founded: "2011",
    teamSize: "200-500",
    website: "plangrid.com",
    features: [
      "Digital blueprint management",
      "Real-time collaboration",
      "Punch list and issue tracking",
      "As-built documentation",
    ],
    useCases: [
      "Field coordination and communication",
      "Quality control inspections",
      "Datacenter construction documentation",
      "Infrastructure project management",
    ],
    relatedIds: ["procore"],
    primaryDivision: "01",
    baseScore: 89,
    averageCost: "$$$$",
    rating: 4.8,
    projectsUsed: 743,
    contactName: "Account Management",
    contactEmail: "accounts@plangrid.com",
    contactPhone: "(415) 555-0133",
  },
  {
    id: "esticom",
    name: "Esticom",
    tagline: "Cloud-based construction estimating",
    description: "Esticom provides cloud-based takeoff and estimating software designed for electrical, mechanical, and general contractors. The platform streamlines the estimating process with digital plan management and automated calculations.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Estimating", "Productivity"],
    region: ["North America"],
    verticals: ["Commercial", "Industrial", "Datacenter"],
    location: "San Diego, CA",
    founded: "2013",
    teamSize: "20-50",
    website: "esticom.com",
    features: [
      "Digital takeoff and measurement",
      "Electrical and MEP estimating",
      "Cloud-based collaboration",
      "Integration with accounting systems",
    ],
    useCases: [
      "Electrical contractor estimating",
      "MEP bid preparation",
      "Datacenter systems estimation",
      "Commercial project takeoffs",
    ],
    relatedIds: ["procore"],
    primaryDivision: "26",
    secondaryDivisions: ["01", "22", "23"],
    baseScore: 83,
    averageCost: "$$",
    rating: 4.4,
    projectsUsed: 456,
    contactName: "Support Team",
    contactEmail: "support@esticom.com",
    contactPhone: "(619) 555-0145",
  },
];
