import type { Solution } from "./solutions";

export const mockSolutions: Solution[] = [
  {
    id: "canvas-robotics",
    name: "Canvas Robotics",
    tagline: "Autonomous drywall finishing robots",
    description: "Canvas develops intelligent robots that automate drywall finishing in commercial construction. Their AI-powered systems work alongside human crews to increase productivity while maintaining quality standards. The robots use advanced sensors and machine learning to navigate job sites and perform precise finishing work.",
    logo: "@assets/generated_images/Canvas_Robotics_company_logo_752c529f.png",
    categories: ["Robotics", "AI", "Productivity"],
    location: "San Francisco, CA",
    founded: "2017",
    teamSize: "50-100",
    website: "canvas.build",
    features: [
      "Autonomous navigation on active job sites",
      "AI-powered quality control and inspection",
      "Seamless integration with existing workflows",
      "Real-time progress tracking and reporting",
    ],
    useCases: [
      "Commercial office buildings",
      "Multi-family residential projects",
      "Healthcare facilities",
      "Educational institutions",
    ],
    relatedIds: ["dusty-robotics", "spot-ai"],
  },
  {
    id: "dusty-robotics",
    name: "Dusty Robotics",
    tagline: "Robotic layout automation for construction",
    description: "Dusty Robotics creates autonomous robots that print precise layout information directly on job site floors. Their FieldPrinter technology eliminates manual measuring and marking, reducing errors and saving significant time on construction projects. The system integrates with BIM models for accurate, real-time layout.",
    logo: "@assets/generated_images/Dusty_Robotics_company_logo_c4a251ad.png",
    categories: ["Robotics", "Productivity"],
    location: "Mountain View, CA",
    founded: "2018",
    teamSize: "30-50",
    website: "dustyrobotics.com",
    features: [
      "BIM-to-field layout automation",
      "Millimeter-level precision printing",
      "Multi-trade coordination visualization",
      "Cloud-based project management",
    ],
    useCases: [
      "MEP coordination and layout",
      "Structural layout verification",
      "Interior partition layout",
      "Quality control inspections",
    ],
    relatedIds: ["canvas-robotics", "cyphra"],
  },
  {
    id: "spot-ai",
    name: "SPOT AI",
    tagline: "AI-powered construction site safety and surveillance",
    description: "SPOT AI provides intelligent video surveillance and safety monitoring for construction sites. Their cloud-based platform uses computer vision and AI to detect safety violations, monitor progress, and enhance site security. The system provides real-time alerts and comprehensive analytics to improve safety outcomes.",
    logo: "@assets/generated_images/SPOT_AI_company_logo_b81b7511.png",
    categories: ["Safety", "AI"],
    location: "San Francisco, CA",
    founded: "2018",
    teamSize: "100-200",
    website: "spot.ai",
    features: [
      "Real-time safety violation detection",
      "PPE compliance monitoring",
      "Automated incident documentation",
      "Intelligent search across video footage",
    ],
    useCases: [
      "Worker safety compliance monitoring",
      "Site security and theft prevention",
      "Progress documentation and timelapse",
      "Quality assurance inspections",
    ],
    relatedIds: ["cyphra", "canvas-robotics"],
  },
  {
    id: "cyphra",
    name: "Cyphra",
    tagline: "AI-driven construction analytics and insights",
    description: "Cyphra leverages artificial intelligence to transform construction data into actionable insights. Their platform analyzes project information from multiple sources to predict delays, optimize schedules, and improve decision-making. The system helps teams identify risks early and maintain project momentum.",
    logo: "@assets/generated_images/Cyphra_company_logo_1a6281cd.png",
    categories: ["AI", "Productivity"],
    location: "Austin, TX",
    founded: "2019",
    teamSize: "20-30",
    website: "cyphra.ai",
    features: [
      "Predictive project analytics",
      "Automated risk identification",
      "Schedule optimization algorithms",
      "Multi-source data integration",
    ],
    useCases: [
      "Project delay prediction and mitigation",
      "Resource allocation optimization",
      "Budget variance analysis",
      "Subcontractor performance tracking",
    ],
    relatedIds: ["spot-ai", "dusty-robotics"],
  },
];
